# Site settings
site: Antal Monori
title: Antal Monori
keywords: blog
description: Thoughts about crafting good code and making great coffee ☕️. Also occasional ramblings about hobbies and travel ✈️.
lang: en-US
timezone:  Europe/London
repo: https://github.com/anthonymonori/website # site repo [optional]

# Author settings
author:
  name: Antal Monori
  bio: Software Engineer @wise <br> Prev. @skyscanner @lego <br> Based in London
  picture: assets/images/profile.jpeg 
  github: anthonymonori # github username
  linkedin: hifromantal # linkedin username
  mastodon: '@antal' # androiddev.social username
  email: antal@monori.me # email adress


# URL settings
url: "http://127.0.0.1:4000" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false