name: Validate

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.3
    - name: Install Jekyll and Bundler
      run: |
        gem install bundler
        bundle install
    - name: Build the Jekyll site
      run: bundle exec jekyll build --trace